{% set name = "ntsm" %}
{% set version = "1.2.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/JustinChu/ntsm/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 465f674c35cd41c4c3e35444c69db52ea2bf4a0ca996c91689545e3e8333e1d9

build:
  skip: true  # [osx or win]
  number: 0
  run_exports:
   - {{ pin_subpackage('ntsm', max_pin="x.x.x") }}

requirements:
  build:
   - {{ compiler('cxx') }}
   - llvm-openmp  # [osx]
   - make
  host:
   - zlib
   - libgomp
  run:
   - llvm-openmp  # [osx]
   - python
   - pyfaidx
   - numpy
   - scikit-learn
   - pandas
   - zlib
   - libgomp
   - make
   - samtools
   - bwa
   - perl

test:
  commands:
   - ntsmCount --help
   - ntsmVCF --help
   - ntsmEval --help
   - ntsmSiteGen test

about:
  home: "https://github.com/JustinChu/ntsm"
  summary: "ntsm - Nucleotide Sequence/Sample Matcher"
  license: "MIT"
  license_family: MIT
  license_file: LICENSE
  dev_url: "https://github.com/JustinChu/ntsm"
  doc_url: "https://github.com/JustinChu/ntsm/blob/{{ version }}/README.md"

extra:
  additional-platforms:
    - linux-aarch64